"""Disposable generated-package materialization and controller-computed source diffs.

The research model returns complete UTF-8 file contents.  It never supplies patches, shell
commands, destination paths, or filesystem references.  This module validates the whole mapping
before creating a new child directory, preserves the in-memory parent, and computes every logical
identity independently of temporary paths and file metadata.
"""

from __future__ import annotations

import ast
import difflib
import hashlib
import math
import os
import shutil
import stat
from collections.abc import Iterable, Mapping
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import cast

from kuairand_agent.candidate_api.runtime_contract import (
    CANDIDATE_RUNTIME_CONTRACT,
    CandidateRuntimeContractError,
)
from kuairand_agent.research.schemas import (
    GeneratedPackage,
    ParentSnapshot,
    ParentSourceFile,
    SchemaValidationError,
    canonical_digest,
    canonical_json_bytes,
    parse_json_object,
)
from kuairand_agent.research.source_policy import (
    DEFAULT_CANDIDATE_SOURCE_POLICY,
    CandidateManifestPolicyError,
)


class CandidateMaterializationError(ValueError):
    """A generated package cannot be safely represented as a disposable source child."""


class CandidateStaticError(ValueError):
    """A materialized child fails syntax, import, or executable-materiality policy."""


def validate_model_generated_overlay(package: GeneratedPackage) -> None:
    """Enforce the immutable runtime-wrapper seam before any generated bytes are written."""

    if not isinstance(package, GeneratedPackage):
        raise CandidateMaterializationError("package must be a GeneratedPackage")
    try:
        CANDIDATE_RUNTIME_CONTRACT.validate_overlay_paths(
            value.path for value in package.files
        )
    except CandidateRuntimeContractError as exc:
        raise CandidateMaterializationError(str(exc)) from exc


@dataclass(frozen=True, slots=True)
class MaterializedCandidate:
    """Path plus logical identities for one immutable disposable child source tree."""

    destination: Path
    parent_digest: str
    package_digest: str
    material_symbols: tuple[str, ...]
    files: tuple[ParentSourceFile, ...]
    changed_paths: tuple[str, ...]
    unified_diff: str
    source_digest: str
    diff_digest: str

    def file(self, path: str) -> ParentSourceFile:
        for value in self.files:
            if value.path == path:
                return value
        raise CandidateMaterializationError(f"materialized child does not contain {path!r}")


@dataclass(frozen=True, slots=True)
class StaticGateResult:
    python_files: tuple[str, ...]
    json_files: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class MaterialChangeEvidence:
    changed_symbols: tuple[str, ...]
    reachable_python_files: tuple[str, ...]


def _validate_path(value: str, *, generated: bool) -> PurePosixPath:
    try:
        return DEFAULT_CANDIDATE_SOURCE_POLICY.validate_path(value, generated=generated)
    except CandidateManifestPolicyError as exc:
        raise CandidateMaterializationError(str(exc)) from exc


def _validate_package(parent: ParentSnapshot, package: GeneratedPackage) -> None:
    if not isinstance(parent, ParentSnapshot):
        raise CandidateMaterializationError("parent must be a ParentSnapshot")
    if not isinstance(package, GeneratedPackage):
        raise CandidateMaterializationError("package must be a GeneratedPackage")
    policy = DEFAULT_CANDIDATE_SOURCE_POLICY
    try:
        policy.validate_manifest(
            (value.path for value in package.files),
            parent_paths=(value.path for value in parent.files),
        )
    except CandidateManifestPolicyError as exc:
        raise CandidateMaterializationError(str(exc)) from exc
    total = 0
    for generated_file in package.files:
        size = len(generated_file.content.encode("utf-8"))
        if size > policy.max_generated_file_bytes:
            raise CandidateMaterializationError(
                f"generated file {generated_file.path!r} exceeds the byte limit"
            )
        total += size
    if total > policy.max_generated_total_bytes:
        raise CandidateMaterializationError("generated package exceeds the total byte limit")


def _tree_digest(files: Iterable[ParentSourceFile]) -> str:
    return canonical_digest(
        {
            "schema_version": 1,
            "files": [
                {"path": value.path, "sha256": value.sha256}
                for value in sorted(files, key=lambda item: item.path)
            ],
        }
    )


_MAX_JSON_LITERAL_NODES = 4_096
_MAX_JSON_LITERAL_DEPTH = 64


def _json_literal_value(node: ast.AST, *, depth: int = 0) -> object:
    """Decode only a bounded JSON-equivalent Python literal; never evaluate code."""

    if depth > _MAX_JSON_LITERAL_DEPTH:
        raise ValueError("JSON-equivalent literal exceeds the nesting limit")
    if isinstance(node, ast.Dict):
        result: dict[str, object] = {}
        for key_node, value_node in zip(node.keys, node.values, strict=True):
            if not isinstance(key_node, ast.Constant) or type(key_node.value) is not str:
                raise ValueError("JSON-equivalent object keys must be strings")
            key = key_node.value
            if key in result:
                raise ValueError("JSON-equivalent object contains duplicate keys")
            result[key] = _json_literal_value(value_node, depth=depth + 1)
        return result
    if isinstance(node, ast.List):
        return [_json_literal_value(item, depth=depth + 1) for item in node.elts]
    if isinstance(node, ast.Constant):
        value = node.value
        if value is None or type(value) in {str, bool, int}:
            return value
        if type(value) is float and math.isfinite(value):
            return value
        raise ValueError("literal contains a non-JSON scalar")
    if (
        isinstance(node, ast.UnaryOp)
        and isinstance(node.op, (ast.UAdd, ast.USub))
        and isinstance(node.operand, ast.Constant)
        and type(node.operand.value) in {int, float}
    ):
        numeric = cast(int | float, node.operand.value)
        value = numeric if isinstance(node.op, ast.UAdd) else -numeric
        if type(value) is float and not math.isfinite(value):
            raise ValueError("literal contains a non-finite number")
        return value
    raise ValueError("literal contains non-JSON syntax")


def _normalize_generated_content(path: str, content: str) -> str:
    if not path.endswith(".json"):
        return content
    try:
        parse_json_object(content)
        return content
    except SchemaValidationError:
        pass
    try:
        expression = ast.parse(content, filename=path, mode="eval")
    except SyntaxError:
        return content
    if sum(1 for _ in ast.walk(expression)) > _MAX_JSON_LITERAL_NODES:
        return content
    try:
        value = _json_literal_value(expression.body)
    except ValueError:
        return content
    if not isinstance(value, dict):
        return content
    return canonical_json_bytes(value).decode("ascii") + "\n"


def _unified_diff(
    parent_files: Mapping[str, str], child_files: Mapping[str, str]
) -> tuple[tuple[str, ...], str]:
    changed = tuple(
        path
        for path in sorted(set(parent_files) | set(child_files))
        if parent_files.get(path) != child_files.get(path)
    )
    fragments: list[str] = []
    for path in changed:
        fragments.extend(
            difflib.unified_diff(
                parent_files.get(path, "").splitlines(keepends=True),
                child_files.get(path, "").splitlines(keepends=True),
                fromfile=f"a/{path}",
                tofile=f"b/{path}",
                lineterm="\n",
            )
        )
    return changed, "".join(fragments)


def _write_exclusive(path: Path, payload: bytes) -> None:
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_CLOEXEC", 0)
    flags |= getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(path, flags, 0o400)
    try:
        offset = 0
        while offset < len(payload):
            offset += os.write(descriptor, payload[offset:])
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _make_read_only(root: Path) -> None:
    for value in sorted(root.rglob("*"), reverse=True):
        metadata = value.lstat()
        if stat.S_ISDIR(metadata.st_mode):
            value.chmod(0o500)
        elif stat.S_ISREG(metadata.st_mode):
            value.chmod(0o400)
        else:  # defensive; this module creates only directories and regular files
            raise CandidateMaterializationError("candidate tree contains a special file")
    root.chmod(0o500)


def _cleanup(root: Path) -> None:
    if not root.exists():
        return
    for value in root.rglob("*"):
        try:
            if value.is_dir():
                value.chmod(0o700)
            else:
                value.chmod(0o600)
        except OSError:
            pass
    with suppress(OSError):
        root.chmod(0o700)
    shutil.rmtree(root, ignore_errors=True)


def materialize_candidate(
    parent: ParentSnapshot,
    package: GeneratedPackage,
    destination: Path | str,
) -> MaterializedCandidate:
    """Create one new read-only child tree after validating the complete response mapping."""

    _validate_package(parent, package)
    destination_path = Path(destination)
    if destination_path.exists() or destination_path.is_symlink():
        raise CandidateMaterializationError(
            f"candidate destination already exists: {destination_path}"
        )
    parent_directory = destination_path.parent
    try:
        metadata = parent_directory.lstat()
    except OSError as exc:
        raise CandidateMaterializationError("candidate destination parent does not exist") from exc
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
        raise CandidateMaterializationError("candidate destination parent must be a real directory")

    described = describe_materialized_candidate(parent, package, destination_path)

    try:
        destination_path.mkdir(mode=0o700, exist_ok=False)
        for value in described.files:
            relative = _validate_path(value.path, generated=False)
            target = destination_path.joinpath(*relative.parts)
            target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
            _write_exclusive(target, value.content.encode("utf-8"))
        _make_read_only(destination_path)
    except (OSError, CandidateMaterializationError) as exc:
        _cleanup(destination_path)
        if isinstance(exc, CandidateMaterializationError):
            raise
        raise CandidateMaterializationError(f"candidate materialization failed: {exc}") from exc

    return MaterializedCandidate(
        destination=destination_path,
        parent_digest=described.parent_digest,
        package_digest=described.package_digest,
        material_symbols=described.material_symbols,
        files=described.files,
        changed_paths=described.changed_paths,
        unified_diff=described.unified_diff,
        source_digest=described.source_digest,
        diff_digest=described.diff_digest,
    )


def describe_materialized_candidate(
    parent: ParentSnapshot,
    package: GeneratedPackage,
    destination: Path | str,
) -> MaterializedCandidate:
    """Compute the exact normalized child identity without touching the filesystem."""

    _validate_package(parent, package)
    parent_content = {value.path: value.content for value in parent.files}
    child_content = dict(parent_content)
    child_content.update(
        {
            value.path: _normalize_generated_content(value.path, value.content)
            for value in package.files
        }
    )
    changed_paths, unified = _unified_diff(parent_content, child_content)
    child_files = tuple(
        ParentSourceFile.create(path, content) for path, content in sorted(child_content.items())
    )
    return MaterializedCandidate(
        destination=Path(destination),
        parent_digest=parent.digest,
        package_digest=package.digest,
        material_symbols=package.material_symbols,
        files=child_files,
        changed_paths=changed_paths,
        unified_diff=unified,
        source_digest=_tree_digest(child_files),
        diff_digest=hashlib.sha256(unified.encode("utf-8")).hexdigest(),
    )


def _verify_materialized_bytes(candidate: MaterializedCandidate) -> None:
    try:
        root_metadata = candidate.destination.lstat()
    except OSError as exc:
        raise CandidateStaticError("materialized candidate directory is missing") from exc
    if stat.S_ISLNK(root_metadata.st_mode) or not stat.S_ISDIR(root_metadata.st_mode):
        raise CandidateStaticError("materialized candidate root must be a real directory")
    expected = {value.path: value for value in candidate.files}
    observed: set[str] = set()
    for path in candidate.destination.rglob("*"):
        metadata = path.lstat()
        if stat.S_ISDIR(metadata.st_mode):
            continue
        relative = path.relative_to(candidate.destination).as_posix()
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise CandidateStaticError(f"candidate tree contains a nonregular file: {relative}")
        try:
            reference = expected[relative]
        except KeyError as exc:
            raise CandidateStaticError(
                f"candidate tree contains an undeclared file: {relative}"
            ) from exc
        try:
            payload = path.read_bytes()
        except OSError as exc:
            raise CandidateStaticError(f"candidate file cannot be read: {relative}") from exc
        if hashlib.sha256(payload).hexdigest() != reference.sha256:
            raise CandidateStaticError(f"candidate file changed after materialization: {relative}")
        observed.add(relative)
    missing = set(expected) - observed
    if missing:
        raise CandidateStaticError(
            f"candidate tree is missing declared file(s): {sorted(missing)!r}"
        )


def _import_root(name: str | None) -> str:
    if not name:
        return ""
    return name.split(".", 1)[0]


def _numpy_aliases(tree: ast.Module) -> tuple[set[str], set[str]]:
    modules: set[str] = set()
    loads: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name == "numpy":
                    modules.add(alias.asname or "numpy")
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module == "numpy":
            for alias in node.names:
                if alias.name == "load":
                    loads.add(alias.asname or "load")
    return modules, loads


def _is_numpy_load_call(node: ast.AST, modules: set[str], loads: set[str]) -> bool:
    if not isinstance(node, ast.Call):
        return False
    function = node.func
    return (
        isinstance(function, ast.Attribute)
        and function.attr == "load"
        and isinstance(function.value, ast.Name)
        and function.value.id in modules
    ) or (isinstance(function, ast.Name) and function.id in loads)


def _returns_context_loaded_array(
    statements: list[ast.stmt],
    bound_name: str,
    numpy_modules: set[str],
) -> bool:
    for statement in statements:
        for node in ast.walk(statement):
            if not isinstance(node, ast.Return) or node.value is None:
                continue
            value = node.value
            if isinstance(value, ast.Name) and value.id == bound_name:
                return True
            if (
                isinstance(value, ast.Call)
                and isinstance(value.func, ast.Attribute)
                and value.func.attr in {"array", "asarray", "ascontiguousarray"}
                and isinstance(value.func.value, ast.Name)
                and value.func.value.id in numpy_modules
                and value.args
                and isinstance(value.args[0], ast.Name)
                and value.args[0].id == bound_name
            ):
                return True
    return False


def _validate_numpy_load_context_managers(path: str, tree: ast.Module) -> None:
    numpy_modules, numpy_loads = _numpy_aliases(tree)
    if not numpy_modules and not numpy_loads:
        return
    for node in ast.walk(tree):
        if not isinstance(node, (ast.With, ast.AsyncWith)):
            continue
        for item in node.items:
            if not _is_numpy_load_call(item.context_expr, numpy_modules, numpy_loads):
                continue
            if not isinstance(item.optional_vars, ast.Name):
                continue
            if _returns_context_loaded_array(node.body, item.optional_vars.id, numpy_modules):
                raise CandidateStaticError(
                    f"np.load result is returned from a context manager in {path!r}; "
                    ".npy files return ndarray objects that are not context managers, while "
                    ".npz archives must be copied before the archive closes"
                )


def _validate_python(path: str, content: str) -> ast.Module:
    try:
        tree = ast.parse(content, filename=path)
    except SyntaxError as exc:
        location = f"line {exc.lineno}" if exc.lineno is not None else "unknown line"
        raise CandidateStaticError(f"invalid Python in {path!r} at {location}: {exc.msg}") from exc
    for node in ast.walk(tree):
        imported: tuple[str, ...] = ()
        if isinstance(node, ast.Import):
            imported = tuple(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.level:
                continue
            imported = (node.module or "",)
        for name in imported:
            if _import_root(name) in DEFAULT_CANDIDATE_SOURCE_POLICY.forbidden_import_roots:
                raise CandidateStaticError(f"forbidden import {name!r} in {path!r}")
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id in DEFAULT_CANDIDATE_SOURCE_POLICY.forbidden_calls
        ):
            raise CandidateStaticError(f"forbidden call {node.func.id!r} in {path!r}")
    _validate_numpy_load_context_managers(path, tree)
    return tree


def validate_candidate_static(candidate: MaterializedCandidate) -> StaticGateResult:
    """Run syntax, JSON, import, and immutable-tree checks after materialization."""

    _verify_materialized_bytes(candidate)
    python_files: list[str] = []
    json_files: list[str] = []
    for value in candidate.files:
        if value.path.endswith(".py"):
            _validate_python(value.path, value.content)
            python_files.append(value.path)
        elif value.path.endswith(".json"):
            try:
                parse_json_object(value.content)
            except SchemaValidationError as exc:
                raise CandidateStaticError(f"invalid JSON in {value.path!r}: {exc}") from exc
            json_files.append(value.path)
    entrypoint = DEFAULT_CANDIDATE_SOURCE_POLICY.final_entrypoint
    if entrypoint not in python_files:
        raise CandidateStaticError(f"candidate tree must contain the {entrypoint} entry point")
    return StaticGateResult(tuple(python_files), tuple(json_files))


class _DocstringStripper(ast.NodeTransformer):
    def _strip(
        self, node: ast.Module | ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef
    ) -> None:
        if (
            node.body
            and isinstance(node.body[0], ast.Expr)
            and isinstance(node.body[0].value, ast.Constant)
            and isinstance(node.body[0].value.value, str)
        ):
            node.body = node.body[1:]

    def visit_Module(self, node: ast.Module) -> ast.AST:
        self.generic_visit(node)
        self._strip(node)
        return node

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.AST:
        self.generic_visit(node)
        self._strip(node)
        return node

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> ast.AST:
        self.generic_visit(node)
        self._strip(node)
        return node

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.AST:
        self.generic_visit(node)
        self._strip(node)
        return node


def _normalized_tree(path: str, content: str) -> ast.Module:
    tree = _validate_python(path, content)
    stripped = _DocstringStripper().visit(tree)
    assert isinstance(stripped, ast.Module)
    return ast.fix_missing_locations(stripped)


def _top_level_symbols(tree: ast.Module) -> dict[str, str]:
    result: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            result[node.name] = ast.dump(node, annotate_fields=True, include_attributes=False)
    return result


def _local_module_candidates(name: str) -> tuple[str, str]:
    base = name.replace(".", "/")
    return f"{base}.py", f"{base}/__init__.py"


def _reachable_python_files(files: Mapping[str, str]) -> tuple[str, ...]:
    if "candidate.py" not in files:
        return ()
    pending = ["candidate.py"]
    reached: set[str] = set()
    while pending:
        path = pending.pop()
        if path in reached:
            continue
        reached.add(path)
        tree = _normalized_tree(path, files[path])
        for node in ast.walk(tree):
            modules: tuple[str, ...] = ()
            if isinstance(node, ast.Import):
                modules = tuple(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                modules = (node.module,)
            for module in modules:
                for candidate in _local_module_candidates(module):
                    if candidate in files and candidate not in reached:
                        pending.append(candidate)
    return tuple(sorted(reached))


def require_material_executable_change(
    parent: ParentSnapshot,
    candidate: MaterializedCandidate,
) -> MaterialChangeEvidence:
    """Require a declared changed symbol in executable source reachable from ``candidate.py``."""

    validate_candidate_static(candidate)
    parent_files = {
        value.path: value.content for value in parent.files if value.path.endswith(".py")
    }
    child_files = {
        value.path: value.content for value in candidate.files if value.path.endswith(".py")
    }
    reachable = _reachable_python_files(child_files)
    changed_by_name: dict[str, str] = {}
    for path in reachable:
        child_tree = _normalized_tree(path, child_files[path])
        child_symbols = _top_level_symbols(child_tree)
        parent_symbols = (
            _top_level_symbols(_normalized_tree(path, parent_files[path]))
            if path in parent_files
            else {}
        )
        for name, subtree in child_symbols.items():
            if parent_symbols.get(name) != subtree:
                qualified = f"{path}:{name}"
                if name in changed_by_name:
                    raise CandidateStaticError(
                        f"declared material symbol {name!r} is ambiguous across reachable files"
                    )
                changed_by_name[name] = qualified
    declared_changes = tuple(
        changed_by_name[name] for name in candidate.material_symbols if name in changed_by_name
    )
    if not declared_changes:
        missing = sorted(set(candidate.material_symbols) - set(changed_by_name))
        raise CandidateStaticError(
            f"declared material symbol(s) did not change material executable-source: {missing!r}"
        )
    return MaterialChangeEvidence(tuple(sorted(declared_changes)), reachable)


def snapshot_materialized_candidate(
    candidate: MaterializedCandidate, *, candidate_id: str
) -> ParentSnapshot:
    """Promote a verified child source record to an immutable parent snapshot for repair/replay."""

    _verify_materialized_bytes(candidate)
    return ParentSnapshot(candidate_id=candidate_id, files=candidate.files)
